### ISSUE TITLE
Support Svelte 4

### ISSUE THREAD

**Issue by ion-ciubaciuc** [gyurielf/svelte-tel-input#168]
Update the dependencies to use Svelte 4.

**Comment by gyurielf** [comment]
Hello there!

It's in progress.
The entire project will be migrated to a monorepo.
The _"hard"_ part is almost done, just CI and Releasing things left.
you can see the progression here, https://github.com/gyurielf/mono-sti

**Comment by gyurielf** [comment]
Svelte 4 has been supported.

https://github.com/gyurielf/svelte-tel-input/pull/173

If you have any issue, feel free to reopen the issue
