### ISSUE TITLE
Example Import  needs an import assertion of type "json"

### ISSUE THREAD

**Issue by JuanSanchezPrink** [gyurielf/svelte-tel-input#191]
This error occurs when refreshing the application
/node_modules/libphonenumber-js/examples.mobile.json" needs an import assertion of type "json".

**Comment by gyurielf** [comment]
Hello there!

Could you provide more information about your environment ?

I can't reproduce this error.

BR,
G.

**Comment by JuanSanchezPrink** [comment]
Hello. this is my package,json

{
	"name": "",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@astrojs/svelte": "^1.0.1",
		"@astrojs/tailwind": "^2.0.2",
		"@iconify-icons/mdi": "^1.2.31",
		"@iconify/json": "^2.1.119",
		"@popperjs/core": "^2.11.6",
		"@rollup/plugin-json": "^6.0.0",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/adapter-static": "^1.0.0-next.44",
		"@sveltejs/kit": "next",
		"astro": "^1.4.6",
		"autoprefixer": "^10.4.12",
		"classnames": "^2.3.2",
		"date-picker-svelte": "^2.2.4",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"flowbite": "^1.5.3",
		"flowbite-svelte": "^0.27.14",
		"postcss": "^8.4.17",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.46.4",
		"svelte-check": "^2.7.1",
		"svelte-dnd-action": "^0.9.22",
		"svelte-loading-spinners": "^0.3.4",
		"svelte-preprocess": "^4.10.7",
		"svelte-simple-datatables": "^0.2.3",
		"tailwindcss": "^3.1.8",
		"typescript": "^4.7.4",
		"vite": "^3.1.0"
	},
	"type": "module",
	"dependencies": {
		"@nanostores/persistent": "^0.7.0",
		"@novacbn/svelte-image-crop": "github:novacbn/svelte-image-crop#0.0.2",
		"@openzeppelin/contracts": "^4.8.0",
		"@unocss/preset-icons": "^0.45.26",
		"@unocss/preset-uno": "^0.45.26",
		"@unocss/preset-web-fonts": "^0.45.26",
		"@unocss/reset": "^0.45.26",
		"apexcharts": "^3.37.0",
		"aws-sdk": "^2.1230.0",
		"axios": "^1.1.0",
		"bcryptjs": "^2.4.3",
		"buffer": "^6.0.3",
		"crypto-js": "^4.1.1",
		"dotenv": "^16.0.3",
		"ethers": "^5",
		"express": "^4.18.2",
		"formidable": "^2.1.1",
		"i18next": "^21.10.0",
		"ipfs-http-client": "^56.0.0",
		"ipfs-mini": "^1.1.5",
		"js-abbreviation-number": "^1.4.0",
		"jsonwebtoken": "^9.0.0",
		"libphonenumber-js": "^1.10.39",
		"mailgun.js": "^8.0.6",
		"mime-types": "^2.1.35",
		"moment": "^2.29.4",
		"mongodb": "^4.10.0",
		"nanostores": "^0.7.0",
		"oauth-1.0a": "^2.2.6",
		"passport": "^0.6.0",
		"passport-twitter-token": "^1.3.0",
		"quill": "^1.3.6",
		"quill-delta-to-html": "^0.12.1",
		"remove": "^0.1.5",
		"sharp": "^0.31.3",
		"solc": "^0.8.17",
		"svelecte": "^3.12.0",
		"svelte-apexcharts": "^1.0.2",
		"svelte-i18n": "^3.6.0",
		"svelte-tags-input": "^3.0.0",
		"svelte-tel-input": "^3.3.1",
		"swiper": "^8.4.3",
		"talkjs": "^0.16.0",
		"twilio": "^4.10.0",
		"twitter-lite": "^1.1.0",
		"unocss": "^0.45.26",
		"unocss-preset-daisy": "^1.2.0",
		"web3.storage": "^4.4.0",
		"xlsx": "^0.18.5"
	}
}

**Comment by gyurielf** [comment]
thanks,
And what is your node version ?

**Comment by JuanSanchezPrink** [comment]
my node version is v18.16.1

**Comment by gyurielf** [comment]
Thanks.
I'll look into it today.

**Comment by gyurielf** [comment]
Well, I couldn't figure out what was causing this.
I've added the assertion, but it's requires at least node v17. So maybe it will be reverted, then we should dive deeper.
