### ISSUE TITLE
Svelte 5

### ISSUE THREAD

**Issue by nijat** [gyurielf/svelte-tel-input#231]
Svelte 5 recently released, do you have any plans to move it? Currently, this repo is blocker for me to move to svelte 5. It would better to support it. 
Thanks in advance.

**Comment by gyurielf** [comment]
Hello there!

It's already on the way.

@nijat 
I can provide quick fix via peerDependency update in the package.json, to resolve the version complain.

Anyway guyz, I'm confused about the future. I decided to make radical changes for version 4.
I'll open a discussion topic about that, and you can say something to the direction.

**Comment by gyurielf** [comment]
It has been released.
https://github.com/gyurielf/svelte-tel-input/releases/tag/svelte-tel-input%403.5.2
