### ISSUE TITLE
deploy examples somewhear

### ISSUE THREAD

**Issue by nosovk** [gyurielf/svelte-tel-input#49]
for example https://vercel.com/
the goal is to provide some component preview

**Comment by gyurielf** [comment]
Hey There!
Sure.
WIP :), just working on another project atm.
I plan to finalize it in this month.

**Comment by gyurielf** [comment]
Sorry but i was full of with todos, but here it is https://svelte-tel-input.vercel.app/
I'll boost the development finally.
